version: '2.0'

services:
  onezone-master:
    extends:
      file: docker-compose-datahub-zone-base.yml
      service: onezone
    environment:
      #ONEPANEL_DEBUG_MODE: "true" # prevents container exit on configuration error
      ONEPANEL_LOG_LEVEL: "info"
      ONEPANEL_BATCH_MODE: "true"
      ONEZONE_CONFIG: |
        cluster:
          domainName: "$DOMAIN_NAME"
          autoDeploy: true
          nodes:
            n1:
              hostname: "onedata00"
            n2:
              hostname: "onedata01"
            n3:
              hostname: "zonedb01"
            n4:
              hostname: "zonedb02"
          managers:
            mainNode: "n1"
            nodes:
              - "n1"
              - "n2"
          workers:
            nodes:
              - "n1"
              - "n2"
          databases:
            nodes:
              - "n1"
              - "n3"
              - "n4"
        onezone:
          name: "EGI DATAHUB"
          domainName: "$DOMAIN_NAME"
        onepanel:
          users:
            "admin":
              password: "${ADMIN1_PASSWORD}"
              userRole: "admin"
            "admin2":
              password: "${ADMIN2_PASSWORD}"
              userRole: "admin"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400